### ISSUE TITLE
Czy ja mam jakieś stare pliki bazy danych?

### ISSUE THREAD

**Issue by KGRozanski** [EKIPA-REMONTOWA/fadein#18]
Wywala błąd ale jak wejdę we wszystkie projekty to projekt się dodał. Wgl miałem jeszcze ten problem ze znakiem zapytania po Film Akcji? i usunąłem ten niewidoczny znak jedną tylde pierdoloną kufa amfa fatima był znak nima!!! Nom, więc może to po prostu stare pliki... ??
![argawr](https://user-images.githubusercontent.com/22533207/27365045-40638ce8-563e-11e7-9988-5732adeea77e.JPG)
![sdfdf](https://user-images.githubusercontent.com/22533207/27365211-1e258c0c-563f-11e7-91dd-b5109e8a2b7c.JPG)

Mam skubańca !! dodała się kropeczka, a  @GabrielJanczak musisz dorzucić plik z bazą bo ten mój z 06.06.17r,

**Comment by GabrielJanczak** [comment]
W mojej wersji już błedu nie ma. Zapomniałem margnąć xD nawet nie wiesz ile to rozkminiałem xD
